# Generated by Django 5.0.4 on 2024-04-25 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0006_userreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'compuser'), (1, 'admin')], default=1, max_length=50),
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_number', models.IntegerField(default=0)),
                ('complainttype', models.CharField(max_length=100)),
                ('noc', models.CharField(max_length=250)),
                ('complaindetails', models.TextField(blank=True)),
                ('compfile', models.ImageField(upload_to='media/doc_file')),
                ('complaintdate_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.category')),
                ('stateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.state')),
                ('subcategory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.subcategory')),
            ],
        ),
    ]
