# Generated by Django 5.0.4 on 2024-04-25 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0007_alter_customuser_user_type_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
