# Generated by Django 5.0.4 on 2024-04-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0009_alter_complaints_admin_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='complainttype',
            field=models.CharField(max_length=250),
        ),
    ]
