# Generated by Django 5.0.4 on 2024-04-29 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0011_complaints_remark_complaints_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'compuser')], default=1, max_length=50),
        ),
        migrations.CreateModel(
            name='ComplaintRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True)),
                ('status', models.CharField(default=0, max_length=250)),
                ('remarkdate', models.DateTimeField(auto_now_add=True)),
                ('comp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.complaints')),
            ],
        ),
    ]
