# Generated by Django 5.0.4 on 2024-04-29 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0012_alter_customuser_user_type_complaintremark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaintremark',
            old_name='comp_id',
            new_name='comp_id_id',
        ),
    ]
